### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by sethships** [zmartzone/liboauth2-sts#1]
I am attempting to build this dependency for mod_sts and am receiving a compile error:

src/sts.c: In function ‘oauth2_sts_cfg_free’:
src/sts.c:240:3: error: implicit declaration of function ‘oauth2_cache_free’; did you mean ‘oauth2_cache_set’? [-Werror=implicit-function-declaration]
   oauth2_cache_free(NULL, cfg->cache);
   ^~~~~~~~~~~~~~~~~
   oauth2_cache_set
src/sts.c: In function ‘sts_cfg_set_cache’:
src/sts.c:410:49: error: passing argument 3 of ‘oauth2_cache_init’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  cfg->cache = oauth2_cache_init(cfg->log, type, options);
                                                 ^~~~~~~
In file included from src/sts.c:27:0:
/usr/local/include/oauth2/cache.h:54:17: note: expected ‘const oauth2_nv_list_t * {aka const struct oauth2_nv_list_t *}’ but argument is of type ‘const char *’
 oauth2_cache_t *oauth2_cache_init(oauth2_log_t *log, const char *type,
                 ^~~~~~~~~~~~~~~~~

I'm following the build instructions from: https://gist.github.com/zamd/24e4dff10ac234162a43908334b2422b

On Ubuntu

**Comment by zandbelt** [comment]
I'm in the middle of updating master; you should use https://github.com/zmartzone/liboauth2/commit/8d829cc058ab40594e2f63e785bc92182b0e763d for now

**Comment by sethships** [comment]
@zandbelt, for mod_sts?

**Comment by zandbelt** [comment]
it should be working now with the master branches of mod_sts, liboauth2-sts and liboauth2

**Comment by sethships** [comment]
Thanks! I have it all compiled. About to start testing/using it.
